yatube/about/urls.py
from django.urls import path
from django.views.generic import TemplateView


app_name = 'about'

urlpatterns = [
    path('author/', TemplateView.as_view(template_name='about/author.html'),
         name='author'),
    path('tech/', TemplateView.as_view(template_name='about/tech.html'),
         name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path('posts/<int:post_id>/comment/',
         views.add_comment,
         name='add_comment'
         ),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

handler404 = 'core.views.page_not_found'
handler403 = 'core.views.forbidden'

urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),

]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models


from core.models import CreatedModel

User = get_user_model()

IMAGE_DIRECTORY = 'posts/'


class Group(models.Model):
    title = models.CharField(max_length=200, verbose_name='Заголовок')
    slug = models.SlugField(unique=True, verbose_name='Слаг')
    description = models.TextField(verbose_name='Описание')

    def __str__(self) -> str:
        return self.title

    class Meta:
        verbose_name = 'Группы',
        verbose_name_plural = 'Группы'


class Post(CreatedModel):
    text = models.TextField(
        verbose_name='Текст поста',
        help_text='Пишите первое что придёт в голову'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='Автор'
    )
    group = models.ForeignKey(
        Group,
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
        related_name='posts',
        verbose_name='Группа',
        help_text='Группа, к которой будет относиться пост'
    )
    image = models.ImageField(
        'Картинка',
        upload_to=IMAGE_DIRECTORY,
        blank=True,
        help_text='Приложите вашу лучшую фотографию'
    )

    def __str__(self) -> str:
        return self.text[:15]

    class Meta:
        ordering = ('-pub_date',)
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'


class Comment(CreatedModel):
    text = models.TextField(
        verbose_name='Текст комметария',
        help_text='Прокоментируйте пост, нам важно ваше мнение'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Автор',
    )
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Комментируемый пост'
    )

    class Meta:
        ordering = ('pub_date',)
        verbose_name = 'Комментарии'
        verbose_name_plural = 'Комментарии'

    def __str__(self) -> str:
        return self.text[:15]


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='follower',
        verbose_name='Кто подписался',
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='following',
        verbose_name='На кого подписался',
    )

    class Meta:
        verbose_name = 'Подписки'

yatube/posts/forms.py
from django import forms

from .models import Comment, Post


class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ('text', 'group', 'image')


class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ('text',)

yatube/posts/views.py
from django.shortcuts import get_object_or_404, redirect, render
from django.contrib.auth.decorators import login_required
from django.core.cache import cache

from .models import Group, Post, User, Follow
from .forms import CommentForm, PostForm
from .utils import get_paginator_pages


def index(request):
    posts = Post.objects.select_related('group', 'author')
    page_obj = get_paginator_pages(posts, request)
    template = 'posts/index.html'
    context = {
        'page_obj': page_obj,
    }
    return render(request, template, context)


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    posts = group.posts.select_related('author', 'group')
    page_obj = get_paginator_pages(posts, request)
    context = {
        'group': group,
        'page_obj': page_obj,
    }
    template = 'posts/group_list.html'
    return render(request, template, context)


def profile(request, username):
    author = get_object_or_404(User, username=username)
    posts = author.posts.select_related('author', 'group')
    following = (
        request.user.is_authenticated
        and request.user != author
        and Follow.objects.filter(user=request.user, author=author)
    )
    page_obj = get_paginator_pages(posts, request)
    template = 'posts/profile.html'
    context = {
        'page_obj': page_obj,
        'author': author,
        'following': following,
    }
    return render(request, template, context)


def post_detail(request, post_id):
    post = get_object_or_404(
        Post.objects.select_related(
            'author',
            'group'
        ),
        id=post_id
    )
    comments = post.comments.select_related('author', 'post')
    template = 'posts/post_detail.html'
    form = CommentForm()
    context = {
        'post': post,
        'form': form,
        'comments': comments,
    }
    return render(request, template, context)


@login_required
def post_create(request):
    template = 'posts/create_post.html'
    form = PostForm(request.POST or None, files=request.FILES or None)
    context = {
        'form': form,
    }
    if not form.is_valid():
        return render(request, template, context)
    new_post = form.save(commit=False)
    new_post.author = request.user
    new_post.save()
    return redirect('posts:profile', request.user)


@login_required
def post_edit(request, post_id):
    template = 'posts/create_post.html'
    post = get_object_or_404(Post, id=post_id)
    if request.user != post.author:
        return redirect('posts:post_detail', post_id)
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
        instance=post)
    if not form.is_valid():
        context = {
            'form': form,
        }
        return render(request, template, context)
    form.save()
    cache.clear()
    return redirect('posts:post_detail', post_id)


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id)


@login_required
def follow_index(request):
    posts = Post.objects.filter(author__following__user=request.user)
    page_obj = get_paginator_pages(posts, request)
    template = 'posts/follow.html'
    context = {
        'page_obj': page_obj,
    }
    return render(request, template, context)


@login_required
def profile_follow(request, username):
    author = get_object_or_404(User, username=username)
    if request.user != author:
        Follow.objects.get_or_create(user=request.user, author=author)
        cache.clear()
    return redirect('posts:profile', username)


@login_required
def profile_unfollow(request, username):
    author = get_object_or_404(User, username=username)
    Follow.objects.get(user=request.user, author=author).delete()
    cache.clear()
    return redirect('posts:profile', username)

yatube/templates/posts/create_post.html
<!-- templates/posts/create_post.html -->
{% extends 'base.html' %}
{% block title %}Новый пост{% endblock %}
{% load user_filters %} 
{% block content %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          {% include 'includes/errors.html' %}
          {% if form.instance.id %}  
            Редактирование поста
          {% else %}
            Новый пост
        </div>
          {% endif %}
        <div class="card-body">
          <form method="post" enctype="multipart/form-data">
          {% csrf_token %}            
          {% include 'includes/forms_creator.html' %}
          <div class="d-flex justify-content-end">
            <button type="submit" class="btn btn-primary">
              {% if form.instance.id %} Сохранить {% else %} Добавить {% endif %}
            </button>
          </div>
        </form>
      </div>
    </div>
  </div>
{% endblock %}

yatube/templates/posts/follow.html
<!-- templates/posts/index.html -->
{% extends 'base.html' %}
{% load cache %}
{% block title %}Последние обновления на сайте{% endblock %}
{% block content %}
  <h1>Подписки</h1>
  {% include 'includes/switcher.html' with follow=True %}
  {% cache 20 follow page_obj.number %}
    {% for post in page_obj %}
      {% include 'includes/post.html' with group_name=True %}
      {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}
  {% endcache %}
  {% include 'posts/includes/paginator.html' %}
{% endblock %}

yatube/templates/posts/group_list.html
<!-- templates/posts/index.html -->
{% extends 'base.html' %}
{% block title %}Записи сообщества{% endblock %}
{% block content %}
  <h1>{{ group.title }}</h1>
  <p>{{ group.description|linebreaksbr }}</p>
  {% for post in page_obj %}
    {% include 'includes/post.html' %}
    {% if not forloop.last %}<hr>{% endif %}
  {% endfor %}
  {% include 'posts/includes/paginator.html' %}
{% endblock %}

yatube/templates/posts/index.html
<!-- templates/posts/index.html -->
{% extends 'base.html' %}
{% load cache %}
{% block title %}Последние обновления на сайте{% endblock %}
{% block content %}
  <h1>Главная страница</h1>
    {% include 'includes/switcher.html' with index=True %}
    {% cache 20 index page_obj.number %}
      {% for post in page_obj %}
        {% include 'includes/post.html' with group_name=True %}
        {% if not forloop.last %}<hr>{% endif %}
      {% endfor %}
    {% endcache %}
  {% include 'posts/includes/paginator.html' %}
{% endblock %}

yatube/templates/posts/post_detail.html
<!-- templates/posts/post_detail.html -->
{% extends 'base.html' %}
{% block title %}Пост {{ post.text | slice:"0:30" }} {% endblock %}
{% load thumbnail %}
{% load user_filters %} 
{% block content %}
  <div class="row">
    <aside class="col-12 col-md-3">
      <ul class="list-group list-group-flush">
        <li class="list-group-item">
          Дата публикации: {{ post.pub_date|date:"d E Y" }}
        </li>
        {% if post.group %}    
        <li class="list-group-item">
          Группа: {{ post.group.title }}
          <a href="{% url 'posts:group_list' post.group.slug %}">
            все записи группы
          </a>
        </li>
        {% endif %} 
        <li class="list-group-item">
          Автор: {{ post.author }}
        </li>
        <li class="list-group-item d-flex justify-content-between align-items-center">
          Всего постов автора:  <span >{{ post.author.posts.count }}</span>
        </li>
        <li class="list-group-item">
          <a href="{% url 'posts:profile' post.author.username %}">
            все посты пользователя
          </a>
        </li>
      </ul>
    </aside>
    <article class="col-12 col-md-9">
      {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
        <img class="card-img my-2" src="{{ im.url }}">
      {% endthumbnail %}
      <p>{{ post.text|linebreaksbr }}</p>
      {% if post.author == user %}
        <a class="btn btn-primary" href="{% url 'posts:post_edit' post.id %}">
          Редактировать запись
        </a>  
      {% endif %}
    </article>

    {% if user.is_authenticated %}
  <div class="card my-4">
    <h5 class="card-header">Добавить комментарий:</h5>
    <div class="card-body">
      <form method="post" action="{% url 'posts:add_comment' post.id %}">
        {% csrf_token %}      
        <div class="form-group mb-2">
          {{ form.text|addclass:"form-control" }}
        </div>
        <button type="submit" class="btn btn-primary">Отправить</button>
      </form>
    </div>
  </div>
  {% endif %}
  {% for comment in comments %}
    <div class="card my-4">
      <div class="card-body">
        <h5>
          <a href="{% url 'posts:profile' comment.author.username %}">
            {{ comment.author.username }}
          </a>
        </h5>
        <a>{{ comment.pub_date }}</a>
        <p>{{ comment.text|linebreaksbr }}</p>
      </div>
    </div>
  {% endfor %} 
  </div>
{% endblock %}

yatube/templates/posts/profile.html
<!-- templates/posts/profile.html -->
{% extends 'base.html' %}
{% load cache %}
{% block title %}Профайл пользователя {{ author.username }} {% endblock %}
{% block content %}
  <div class="mb-5">
    <h1>Все посты пользователя {{ author.username }}</h1>
    <h3>Всего постов: {{ page_obj.paginator.count }}</h3>   
    {% if author.username != user.username %}
      {% if following %}
      <a
        class="btn btn-lg btn-light"
        href="{% url 'posts:profile_unfollow' author.username %}" role="button"
      >
        Отписаться
      </a>
      {% else %}
        <a
          class="btn btn-lg btn-primary"
          href="{% url 'posts:profile_follow' author.username %}" role="button"
        >
          Подписаться
        </a>
    {% endif %}
  {% endif %}
  <hr>
  {% cache 20 profile page_obj.number %}
    {% for post in page_obj %}
      {% include 'includes/post.html' with group_name=True profile=True %}
      {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}
  {% endcache %}
  {% include 'posts/includes/paginator.html' %}
  </div>
{% endblock %}